### PR TITLE
Webpacker 3.0.0 with fixes

### PR DESCRIPTION
**Pull request by IgorDmitriev**
Catch up on fixes for new version of gem.

Most important this one:
```
Webpacker.compile would always return manifest.refresh even if compiler.compile failed. This means deploys would succeed even if compiling failed.
```
https://github.com/rails/webpacker/pull/728

### CODE REVIEW

**Comment by bcassedy** [comment]
LGTM. I thought we were already on 3?

**Comment by IgorDmitriev** [comment]
@bcassedy since yesterday yes)) but this is some closed PR's that came in during the night. I highlighted the most important, imo, why we should catch up.

**Comment by bcassedy** [comment]
Gotcha. I'm still a little confused. Why then is the gemfile.lock changing from 2 to 3 in this PR if we're already on 3?

**Comment by IgorDmitriev** [comment]
It's a very good questions, and here is the answer: https://github.com/rails/webpacker/pull/718

They forgot to update gemfile.lock yesterday.

**Pull request merged**
